# Generated by Django 4.1.4 on 2022-12-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txt_extract_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
